spring:
  application:
    name: APIGateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:

        - id: booking-route

          uri: lb://BOOKINGMANAGEMENT

          predicates:

            - Path=/api/bookings-management/**


        - id: service-provider-route

          uri: lb://SERVICEPROVIDERMANAGEMENT

          predicates:

            - Path=/api/v1/service-provider/**

        - id: user-management-route
          uri: lb://USERMANAGEMENT
          predicates:
            - Path=/user-management/**




server:
  port: 9999


management:
  endpoint:

    gateway:
      enabled: true



